video_path: /scratch-scc/projects/mthesis_s_kouomnankam/video_tracking_thesis/data/video_side/GX010044.MP4
output_csv: /scratch-scc/projects/mthesis_s_kouomnankam/video_tracking_thesis/outputs/results_detectron2.csv

start_frame: 0
end_frame: 100000

resize_width: 960
resize_height: 540

enable_deflicker: true
enable_tracking: true
enable_bed_edge: true

save_debug_frames: true
debug_dir: /scratch-scc/projects/mthesis_s_kouomnankam/video_tracking_thesis/outputs/debug_detectron2

segmentation_mode: detectron2
device: cpu

detectron2_config_file: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
detectron2_weights_file: COCO
detectron2_score_threshold: 0.5

pipe_roi: [100, 50, 700, 400]
bed_roi: [100, 100, 700, 300]
bed_edge_roi: [100, 100, 700, 300]

save_summary: true
summary_csv: /scratch-scc/projects/mthesis_s_kouomnankam/video_tracking_thesis/outputs/summary_detectron2.csv

deflicker_fps: 200.0
deflicker_freq: 50.0
deflicker_use_second_harmonic: false
deflicker_window_size: 256
deflicker_min_history: 32
deflicker_smooth_alpha: 0.2
deflicker_use_median: true
deflicker_roi: null


