video_path: /mnt/ceph-hdd/projects/mthesis_s_kouomnankam/video_tracking_thesis/data/video_side/GX010262.MP4

output_csv: /mnt/ceph-hdd/projects/mthesis_s_kouomnankam/video_tracking_thesis/outputs/test_inner_pipe_cv/results.csv

optical_flow_csv: /mnt/ceph-hdd/projects/mthesis_s_kouomnankam/video_tracking_thesis/outputs/Lucas_Kanade_CPU8/GX010262_lucas_kanade.csv

start_frame: 0
end_frame: 110000

resize_width: 1280
resize_height: 720

enable_deflicker: true
enable_tracking: true
enable_bed_edge: true
enable_inner_pipe: true
enable_optical_flow: true
optical_flow_use_blur: true
optical_flow_use_equalize: true
enable_optical_box: false

save_debug_frames: true

debug_dir: /mnt/ceph-hdd/projects/mthesis_s_kouomnankam/video_tracking_thesis/outputs/test_inner_pipe_cv/debug

segmentation_mode: bed_cv
segmentation_color_mode: hsv_v

device: cpu

# =========================================================
# Optical Flow Punkte
# =========================================================
optical_flow_points:
  # innere Rohr-/Reflexionsstruktur
  - [500, 315]
  - [600, 315]
  - [700, 315]

  # Bettkante / Partikelbett-Oberkante
  - [800, 310]
  - [950, 310]
  - [1100, 310]
optical_flow_snap_radius: 25
optical_flow_max_jump_px: 5.0
optical_flow_max_fb_error: 2.0
# =========================================================
# ROI Definitionen
# =========================================================
inner_pipe_roi: [470, 345, 260, 60]
bed_roi: [755, 370, 430, 70]
bed_edge_roi: [755, 360, 430, 35]
optical_box_roi: [450, 250, 760, 190]

# =========================================================
# Bettkante
# =========================================================
bed_edge_color_mode: hsv_v

bed_edge_smoothing: true
bed_edge_median_window: 7
bed_edge_ema_alpha: 0.2

# =========================================================
# Ergebnisse
# =========================================================
save_summary: true

summary_csv: /mnt/ceph-hdd/projects/mthesis_s_kouomnankam/video_tracking_thesis/outputs/test_inner_pipe_cv/summary.csv

# =========================================================
# Deflicker
# =========================================================
deflicker_fps: 200.0
deflicker_freq: 50.0

deflicker_use_second_harmonic: true

deflicker_window_size: 256
deflicker_min_history: 32

deflicker_smooth_alpha: 0.2

deflicker_use_median: true

deflicker_roi: null