#!/usr/bin/env python3
"""
evaluate_ground_truth_GX010129.py
=================================

Quantitative internal validation of the GX010129 segmentation results.

The script compares manually annotated binary ground-truth masks against
the corresponding binary masks generated by the video-processing pipeline.

Two semantic regions are evaluated independently:

    1. inner_pipe
    2. particle_bed

The existing repository functions

    src.evaluation.compute_iou()
    src.evaluation.compute_dice()

are reused for the actual segmentation metrics.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import cv2
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.evaluation import compute_dice, compute_iou


# =============================================================================
# Repository-specific paths
# =============================================================================

ROOT = Path("data_gt/ground_truth/GX010129")

GROUND_TRUTH_ROOT = ROOT / "ground_truth"
PREDICTION_ROOT = ROOT / "predictions"

GT_INNER_PIPE_DIR = GROUND_TRUTH_ROOT / "inner_pipe"
GT_PARTICLE_BED_DIR = GROUND_TRUTH_ROOT / "particle_bed"

PRED_INNER_PIPE_DIR = PREDICTION_ROOT / "inner_pipe"
PRED_PARTICLE_BED_DIR = PREDICTION_ROOT / "particle_bed"

OUTPUT_DIR = Path(
    "results/internal_validation/GX010129"
)

PER_FRAME_CSV = OUTPUT_DIR / "per_frame_metrics.csv"
SUMMARY_CSV = OUTPUT_DIR / "summary_metrics.csv"
SUMMARY_TXT = OUTPUT_DIR / "validation_summary.txt"

OVERLAY_DIR = OUTPUT_DIR / "overlays"


# =============================================================================
# Evaluated classes
# =============================================================================

CLASS_CONFIG = {
    "inner_pipe": {
        "gt_dir": GT_INNER_PIPE_DIR,
        "prediction_dir": PRED_INNER_PIPE_DIR,
        "gt_suffix": "_inner_pipe_gt.png",
        "prediction_suffix": "_inner_pipe.png",
    },
    "particle_bed": {
        "gt_dir": GT_PARTICLE_BED_DIR,
        "prediction_dir": PRED_PARTICLE_BED_DIR,
        "gt_suffix": "_particle_bed_gt.png",
        "prediction_suffix": "_particle_bed.png",
    },
}


# =============================================================================
# Utility functions
# =============================================================================

def ensure_output_directory() -> None:
    """Create all required output directories."""

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    OVERLAY_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )


def validate_directories() -> None:
    """Validate all required input directories."""

    directories = [
        GT_INNER_PIPE_DIR,
        GT_PARTICLE_BED_DIR,
        PRED_INNER_PIPE_DIR,
        PRED_PARTICLE_BED_DIR,
    ]

    missing = [
        directory
        for directory in directories
        if not directory.is_dir()
    ]

    if missing:
        message = "\n".join(
            str(path)
            for path in missing
        )

        raise FileNotFoundError(
            "Required directories are missing:\n"
            f"{message}"
        )


def load_binary_mask(path: Path) -> np.ndarray:
    """
    Load a segmentation mask and convert it to a binary uint8 mask.

    Any non-zero pixel is interpreted as foreground.
    """

    mask = cv2.imread(
        str(path),
        cv2.IMREAD_GRAYSCALE,
    )

    if mask is None:
        raise RuntimeError(
            f"Mask could not be read:\n{path}"
        )

    binary = np.where(
        mask > 0,
        255,
        0,
    ).astype(np.uint8)

    return binary


def extract_frame_name(
    gt_path: Path,
    gt_suffix: str,
) -> str:
    """
    Extract the frame identifier from a ground-truth filename.

    Example:
        frame_015000_inner_pipe_gt.png
        -> frame_015000
    """

    filename = gt_path.name

    if not filename.endswith(gt_suffix):
        raise ValueError(
            f"Unexpected GT filename: {filename}"
        )

    return filename[:-len(gt_suffix)]


def frame_number_from_name(frame_name: str) -> int:
    """
    Convert 'frame_015000' to integer 15000.
    """

    prefix = "frame_"

    if not frame_name.startswith(prefix):
        raise ValueError(
            f"Unexpected frame name: {frame_name}"
        )

    return int(frame_name[len(prefix):])


def compute_pixel_statistics(
    gt_mask: np.ndarray,
    prediction_mask: np.ndarray,
) -> dict[str, float]:
    """
    Calculate foreground, intersection, union, ratio, and coverage values.
    """

    gt_bool = gt_mask.astype(bool)
    prediction_bool = prediction_mask.astype(bool)

    intersection = np.logical_and(
        gt_bool,
        prediction_bool,
    )

    union = np.logical_or(
        gt_bool,
        prediction_bool,
    )

    gt_pixels = int(
        np.count_nonzero(gt_bool)
    )

    prediction_pixels = int(
        np.count_nonzero(prediction_bool)
    )

    intersection_pixels = int(
        np.count_nonzero(intersection)
    )

    union_pixels = int(
        np.count_nonzero(union)
    )

    prediction_gt_ratio = (
        prediction_pixels / gt_pixels
        if gt_pixels > 0
        else np.nan
    )

    gt_coverage = (
        intersection_pixels / gt_pixels
        if gt_pixels > 0
        else np.nan
    )

    return {
        "gt_pixels": gt_pixels,
        "prediction_pixels": prediction_pixels,
        "intersection_pixels": intersection_pixels,
        "union_pixels": union_pixels,
        "prediction_gt_ratio": prediction_gt_ratio,
        "gt_coverage": gt_coverage,
    }


def save_segmentation_overlay(
    gt_mask: np.ndarray,
    prediction_mask: np.ndarray,
    output_path: Path,
) -> None:
    """
    Save a qualitative segmentation comparison.

    Colors:
        Green = true positive
        Red   = false negative
        Blue  = false positive
        Black = true negative
    """

    gt = gt_mask > 0
    prediction = prediction_mask > 0

    true_positive = np.logical_and(
        gt,
        prediction,
    )

    false_negative = np.logical_and(
        gt,
        np.logical_not(prediction),
    )

    false_positive = np.logical_and(
        np.logical_not(gt),
        prediction,
    )

    overlay = np.zeros(
        (
            gt.shape[0],
            gt.shape[1],
            3,
        ),
        dtype=np.uint8,
    )

    # OpenCV uses BGR channel order.
    overlay[true_positive] = (
        0,
        255,
        0,
    )

    overlay[false_negative] = (
        0,
        0,
        255,
    )

    overlay[false_positive] = (
        255,
        0,
        0,
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    success = cv2.imwrite(
        str(output_path),
        overlay,
    )

    if not success:
        raise RuntimeError(
            f"Could not write overlay image:\n"
            f"{output_path}"
        )


# =============================================================================
# Per-class evaluation
# =============================================================================

def evaluate_class(
    class_name: str,
    config: dict[str, Any],
) -> list[dict[str, Any]]:
    """
    Evaluate one semantic class for all available GT masks.
    """

    gt_dir = Path(config["gt_dir"])
    prediction_dir = Path(
        config["prediction_dir"]
    )

    gt_suffix = str(
        config["gt_suffix"]
    )

    prediction_suffix = str(
        config["prediction_suffix"]
    )

    gt_files = sorted(
        gt_dir.glob(
            f"*{gt_suffix}"
        )
    )

    if not gt_files:
        raise FileNotFoundError(
            f"No GT masks found for {class_name} in:\n"
            f"{gt_dir}"
        )

    print()
    print("=" * 80)
    print(
        f"Evaluating class: {class_name}"
    )
    print("=" * 80)

    rows: list[dict[str, Any]] = []

    for index, gt_path in enumerate(
        gt_files,
        start=1,
    ):
        frame_name = extract_frame_name(
            gt_path,
            gt_suffix,
        )

        frame_number = frame_number_from_name(
            frame_name
        )

        prediction_path = (
            prediction_dir
            / f"{frame_name}{prediction_suffix}"
        )

        if not prediction_path.is_file():
            print(
                f"[WARNING] Missing prediction: "
                f"{prediction_path.name}"
            )

            rows.append(
                {
                    "frame": frame_number,
                    "frame_name": frame_name,
                    "class": class_name,
                    "status": "missing_prediction",
                    "iou": np.nan,
                    "dice": np.nan,
                    "gt_pixels": np.nan,
                    "prediction_pixels": np.nan,
                    "intersection_pixels": np.nan,
                    "union_pixels": np.nan,
                    "prediction_gt_ratio": np.nan,
                    "gt_coverage": np.nan,
                }
            )

            continue

        gt_mask = load_binary_mask(
            gt_path
        )

        prediction_mask = load_binary_mask(
            prediction_path
        )

        if gt_mask.shape != prediction_mask.shape:
            gt_h, gt_w = gt_mask.shape[:2]
            pred_h, pred_w = prediction_mask.shape[:2]

            gt_aspect = gt_w / gt_h
            pred_aspect = pred_w / pred_h

            if not np.isclose(
                gt_aspect,
                pred_aspect,
                rtol=1e-3,
            ):
                raise ValueError(
                    f"Mask aspect-ratio mismatch for "
                    f"{frame_name} / {class_name}: "
                    f"GT={gt_mask.shape}, "
                    f"Prediction={prediction_mask.shape}"
                )

            print(
                f"Resizing prediction mask for "
                f"{frame_name} / {class_name}: "
                f"{pred_w}x{pred_h} -> "
                f"{gt_w}x{gt_h}"
            )

            prediction_mask = cv2.resize(
                prediction_mask,
                (gt_w, gt_h),
                interpolation=cv2.INTER_NEAREST,
            )

            prediction_mask = np.where(
                prediction_mask > 0,
                255,
                0,
            ).astype(np.uint8)

        pixel_stats = compute_pixel_statistics(
            gt_mask,
            prediction_mask,
        )

        iou = compute_iou(
            gt_mask,
            prediction_mask,
        )

        dice = compute_dice(
            gt_mask,
            prediction_mask,
        )

        overlay_path = (
            OVERLAY_DIR
            / class_name
            / f"{frame_name}_overlay.png"
        )

        save_segmentation_overlay(
            gt_mask=gt_mask,
            prediction_mask=prediction_mask,
            output_path=overlay_path,
        )

        row = {
            "frame": frame_number,
            "frame_name": frame_name,
            "class": class_name,
            "status": "ok",
            "iou": float(iou),
            "dice": float(dice),
            **pixel_stats,
        }

        rows.append(row)

        print(
            f"[{index:02d}/{len(gt_files):02d}] "
            f"{frame_name} | "
            f"IoU={iou:.6f} | "
            f"Dice={dice:.6f} | "
            f"GT={pixel_stats['gt_pixels']} px | "
            f"Pred={pixel_stats['prediction_pixels']} px | "
            f"Ratio={pixel_stats['prediction_gt_ratio']:.4f} | "
            f"Coverage={pixel_stats['gt_coverage']:.4f}"
        )

    return rows


# =============================================================================
# Summary calculation
# =============================================================================

def summarize_metrics(
    frame: pd.DataFrame,
) -> pd.DataFrame:
    """
    Calculate descriptive statistics per semantic class.
    """

    successful = frame.loc[
        frame["status"] == "ok"
    ].copy()

    if successful.empty:
        raise RuntimeError(
            "No successful segmentation comparisons "
            "are available."
        )

    rows: list[dict[str, Any]] = []

    for class_name in sorted(
        successful["class"].unique()
    ):
        subset = successful.loc[
            successful["class"] == class_name
        ]

        iou = pd.to_numeric(
            subset["iou"],
            errors="coerce",
        ).dropna()

        dice = pd.to_numeric(
            subset["dice"],
            errors="coerce",
        ).dropna()

        gt_pixels = pd.to_numeric(
            subset["gt_pixels"],
            errors="coerce",
        ).dropna()

        prediction_pixels = pd.to_numeric(
            subset["prediction_pixels"],
            errors="coerce",
        ).dropna()

        prediction_gt_ratio = pd.to_numeric(
            subset["prediction_gt_ratio"],
            errors="coerce",
        ).dropna()

        gt_coverage = pd.to_numeric(
            subset["gt_coverage"],
            errors="coerce",
        ).dropna()

        row = {
            "class": class_name,
            "num_frames": int(len(subset)),
            "mean_iou": float(iou.mean()),
            "median_iou": float(iou.median()),
            "std_iou": float(iou.std(ddof=0)),
            "min_iou": float(iou.min()),
            "max_iou": float(iou.max()),
            "mean_dice": float(dice.mean()),
            "median_dice": float(dice.median()),
            "std_dice": float(dice.std(ddof=0)),
            "min_dice": float(dice.min()),
            "max_dice": float(dice.max()),
            "mean_gt_pixels": float(
                gt_pixels.mean()
            ),
            "mean_prediction_pixels": float(
                prediction_pixels.mean()
            ),
            "mean_prediction_gt_ratio": float(
                prediction_gt_ratio.mean()
            ),
            "mean_gt_coverage": float(
                gt_coverage.mean()
            ),
        }

        rows.append(row)

    return pd.DataFrame(rows)


# =============================================================================
# Plots
# =============================================================================

def plot_metric(
    frame: pd.DataFrame,
    class_name: str,
    metric: str,
    output_path: Path,
) -> None:
    """Plot one metric over selected frame numbers."""

    subset = frame.loc[
        (
            frame["class"] == class_name
        )
        & (
            frame["status"] == "ok"
        )
    ].copy()

    subset = subset.sort_values(
        "frame"
    )

    if subset.empty:
        return

    x = pd.to_numeric(
        subset["frame"],
        errors="coerce",
    )

    y = pd.to_numeric(
        subset[metric],
        errors="coerce",
    )

    fig = plt.figure(
        figsize=(10, 5)
    )

    axis = fig.add_subplot(111)

    axis.plot(
        x,
        y,
        marker="o",
    )

    axis.axhline(
        float(y.mean()),
        linestyle="--",
        label=f"Mean = {y.mean():.4f}",
    )

    axis.set_xlabel(
        "Video frame"
    )

    axis.set_ylabel(
        metric.upper()
    )

    axis.set_title(
        f"GX010129 - "
        f"{class_name.replace('_', ' ')} "
        f"{metric.upper()}"
    )

    axis.set_ylim(
        0.0,
        1.05,
    )

    axis.grid(
        True,
        alpha=0.3,
    )

    axis.legend()

    fig.tight_layout()

    fig.savefig(
        output_path,
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(fig)


def create_plots(
    frame: pd.DataFrame,
) -> None:
    """Generate IoU and Dice plots for both classes."""

    for class_name in CLASS_CONFIG:
        plot_metric(
            frame,
            class_name,
            "iou",
            OUTPUT_DIR
            / f"{class_name}_iou.png",
        )

        plot_metric(
            frame,
            class_name,
            "dice",
            OUTPUT_DIR
            / f"{class_name}_dice.png",
        )


# =============================================================================
# Text summary
# =============================================================================

def save_text_summary(
    summary: pd.DataFrame,
) -> None:
    """Write a human-readable validation summary."""

    lines = [
        "GX010129 Internal Segmentation Validation",
        "=" * 60,
        "",
        "Metrics:",
        "  IoU  = intersection / union",
        "  Dice = 2 * intersection / "
        "(GT + prediction)",
        "  Prediction/GT ratio = prediction pixels "
        "/ GT pixels",
        "  GT coverage = intersection pixels "
        "/ GT pixels",
        "",
    ]

    for _, row in summary.iterrows():
        class_name = str(
            row["class"]
        )

        lines.extend(
            [
                f"Class: {class_name}",
                f"  Frames:                 "
                f"{int(row['num_frames'])}",
                f"  Mean IoU:               "
                f"{row['mean_iou']:.6f}",
                f"  Median IoU:             "
                f"{row['median_iou']:.6f}",
                f"  Std IoU:                "
                f"{row['std_iou']:.6f}",
                f"  Min IoU:                "
                f"{row['min_iou']:.6f}",
                f"  Max IoU:                "
                f"{row['max_iou']:.6f}",
                f"  Mean Dice:              "
                f"{row['mean_dice']:.6f}",
                f"  Median Dice:            "
                f"{row['median_dice']:.6f}",
                f"  Std Dice:               "
                f"{row['std_dice']:.6f}",
                f"  Min Dice:               "
                f"{row['min_dice']:.6f}",
                f"  Max Dice:               "
                f"{row['max_dice']:.6f}",
                f"  Mean prediction/GT:     "
                f"{row['mean_prediction_gt_ratio']:.6f}",
                f"  Mean GT coverage:       "
                f"{row['mean_gt_coverage']:.6f}",
                "",
            ]
        )

    SUMMARY_TXT.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )


# =============================================================================
# Console summary
# =============================================================================

def print_summary(
    summary: pd.DataFrame,
) -> None:
    """Print evaluation results to the terminal."""

    print()
    print("=" * 80)
    print(
        "GX010129 Internal Segmentation "
        "Validation Summary"
    )
    print("=" * 80)

    for _, row in summary.iterrows():
        print()
        print(
            f"Class: {row['class']}"
        )

        print(
            f"Frames:                "
            f"{int(row['num_frames'])}"
        )

        print(
            f"Mean IoU:              "
            f"{row['mean_iou']:.6f}"
        )

        print(
            f"Median IoU:            "
            f"{row['median_iou']:.6f}"
        )

        print(
            f"Std IoU:               "
            f"{row['std_iou']:.6f}"
        )

        print(
            f"Min IoU:               "
            f"{row['min_iou']:.6f}"
        )

        print(
            f"Max IoU:               "
            f"{row['max_iou']:.6f}"
        )

        print(
            f"Mean Dice:             "
            f"{row['mean_dice']:.6f}"
        )

        print(
            f"Median Dice:           "
            f"{row['median_dice']:.6f}"
        )

        print(
            f"Std Dice:              "
            f"{row['std_dice']:.6f}"
        )

        print(
            f"Min Dice:              "
            f"{row['min_dice']:.6f}"
        )

        print(
            f"Max Dice:              "
            f"{row['max_dice']:.6f}"
        )

        print(
            f"Mean prediction/GT:    "
            f"{row['mean_prediction_gt_ratio']:.6f}"
        )

        print(
            f"Mean GT coverage:      "
            f"{row['mean_gt_coverage']:.6f}"
        )

    print()
    print("Output directory:")
    print(
        f"  {OUTPUT_DIR}"
    )


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    """Program entry point."""

    validate_directories()
    ensure_output_directory()

    all_rows: list[dict[str, Any]] = []

    for class_name, config in CLASS_CONFIG.items():
        class_rows = evaluate_class(
            class_name,
            config,
        )

        all_rows.extend(class_rows)

    if not all_rows:
        raise RuntimeError(
            "No evaluation rows were generated."
        )

    per_frame = pd.DataFrame(
        all_rows
    )

    per_frame = per_frame.sort_values(
        [
            "class",
            "frame",
        ]
    ).reset_index(
        drop=True
    )

    per_frame.to_csv(
        PER_FRAME_CSV,
        index=False,
    )

    summary = summarize_metrics(
        per_frame
    )

    summary.to_csv(
        SUMMARY_CSV,
        index=False,
    )

    create_plots(
        per_frame
    )

    save_text_summary(
        summary
    )

    print_summary(
        summary
    )


if __name__ == "__main__":
    main()