#!/usr/bin/env python3
"""
extract_ground_truth_frames_GX010129.py
=======================================

Prepare representative frames from GX010129.MP4 for manual
ground-truth annotation of

    1. particle bed
    2. inner pipe

The script extracts selected original video frames and copies the
corresponding binary prediction masks already generated by the pipeline.

Output structure
----------------

data/ground_truth/GX010129/
├── frames/
│   ├── frame_000000.png
│   ├── frame_001500.png
│   └── ...
│
├── predictions/
│   ├── particle_bed/
│   │   ├── frame_000000_particle_bed.png
│   │   └── ...
│   │
│   └── inner_pipe/
│       ├── frame_000000_inner_pipe.png
│       └── ...
│
├── ground_truth/
│   ├── particle_bed/
│   │   ├── frame_000000_particle_bed_gt.png
│   │   └── ...
│   │
│   └── inner_pipe/
│       ├── frame_000000_inner_pipe_gt.png
│       └── ...
│
└── selected_frames.csv

The ground-truth directories are initially empty. The masks must be
created manually after the selected original frames have been inspected.

Mask convention
---------------

0   = background
255 = object

Author
------
Serge Kouomnankam
"""

from __future__ import annotations

import csv
import shutil
from pathlib import Path

import cv2


# =============================================================================
# Repository-specific paths
# =============================================================================

VIDEO_PATH = Path(
    "/mnt/ceph-hdd/projects/mthesis_s_kouomnankam/"
    "video_tracking_thesis/data/Validation/GX010129.MP4"
)

PIPELINE_MASK_ROOT = Path(
    "/mnt/ceph-hdd/projects/mthesis_s_kouomnankam/"
    "video_tracking_thesis/outputs/Internal_Validation_GX010129/"
    "masks"
)

PARTICLE_BED_PREDICTION_DIR = (
    PIPELINE_MASK_ROOT / "particle_bed"
)

INNER_PIPE_PREDICTION_DIR = (
    PIPELINE_MASK_ROOT / "inner_pipe"
)

OUTPUT_ROOT = Path(
    "/mnt/ceph-hdd/projects/mthesis_s_kouomnankam/"
    "video_tracking_thesis/data/ground_truth/GX010129"
)

FRAME_OUTPUT_DIR = (
    OUTPUT_ROOT / "frames"
)

PREDICTION_ROOT = (
    OUTPUT_ROOT / "predictions"
)

PARTICLE_BED_PREDICTION_OUTPUT_DIR = (
    PREDICTION_ROOT / "particle_bed"
)

INNER_PIPE_PREDICTION_OUTPUT_DIR = (
    PREDICTION_ROOT / "inner_pipe"
)

GROUND_TRUTH_ROOT = (
    OUTPUT_ROOT / "ground_truth"
)

PARTICLE_BED_GT_DIR = (
    GROUND_TRUTH_ROOT / "particle_bed"
)

INNER_PIPE_GT_DIR = (
    GROUND_TRUTH_ROOT / "inner_pipe"
)

MANIFEST_CSV = (
    OUTPUT_ROOT / "selected_frames.csv"
)


# =============================================================================
# Selected frames
# =============================================================================
#
# 24 frames distributed across the available mask range:
# frame 0 ... frame 34159
#
# The selection is intended to cover the recording instead of evaluating
# only one short sequence.
#
# After extraction, the frames should still be visually inspected.
# Frames with unclear object boundaries may be replaced before annotation.
# =============================================================================

SELECTED_FRAMES = [
    0,
    1500,
    3000,
    4500,
    6000,
    7500,
    9000,
    10500,
    12000,
    13500,
    15000,
    16500,
    18000,
    19500,
    21000,
    22500,
    24000,
    25500,
    27000,
    28500,
    30000,
    31500,
    33000,
    34159,
]


# =============================================================================
# Directory handling
# =============================================================================

def create_directories() -> None:
    """Create all output directories required for annotation."""

    directories = [
        FRAME_OUTPUT_DIR,
        PARTICLE_BED_PREDICTION_OUTPUT_DIR,
        INNER_PIPE_PREDICTION_OUTPUT_DIR,
        PARTICLE_BED_GT_DIR,
        INNER_PIPE_GT_DIR,
    ]

    for directory in directories:
        directory.mkdir(
            parents=True,
            exist_ok=True,
        )


# =============================================================================
# File-name helpers
# =============================================================================

def frame_output_path(
    frame_number: int,
) -> Path:
    """Return output path of an extracted original video frame."""

    return (
        FRAME_OUTPUT_DIR
        / f"frame_{frame_number:06d}.png"
    )


def particle_bed_prediction_source_path(
    frame_number: int,
) -> Path:
    """Return original pipeline particle-bed mask path."""

    return (
        PARTICLE_BED_PREDICTION_DIR
        / f"frame_{frame_number:06d}_particle_bed.png"
    )


def particle_bed_prediction_output_path(
    frame_number: int,
) -> Path:
    """Return copied particle-bed prediction path."""

    return (
        PARTICLE_BED_PREDICTION_OUTPUT_DIR
        / f"frame_{frame_number:06d}_particle_bed.png"
    )


def inner_pipe_prediction_source_path(
    frame_number: int,
) -> Path:
    """Return original pipeline inner-pipe mask path."""

    return (
        INNER_PIPE_PREDICTION_DIR
        / f"frame_{frame_number:06d}_inner_pipe.png"
    )


def inner_pipe_prediction_output_path(
    frame_number: int,
) -> Path:
    """Return copied inner-pipe prediction path."""

    return (
        INNER_PIPE_PREDICTION_OUTPUT_DIR
        / f"frame_{frame_number:06d}_inner_pipe.png"
    )


def particle_bed_gt_path(
    frame_number: int,
) -> Path:
    """Return expected manual particle-bed ground-truth mask path."""

    return (
        PARTICLE_BED_GT_DIR
        / f"frame_{frame_number:06d}_particle_bed_gt.png"
    )


def inner_pipe_gt_path(
    frame_number: int,
) -> Path:
    """Return expected manual inner-pipe ground-truth mask path."""

    return (
        INNER_PIPE_GT_DIR
        / f"frame_{frame_number:06d}_inner_pipe_gt.png"
    )


# =============================================================================
# Input validation
# =============================================================================

def validate_inputs() -> None:
    """Check whether all required source data are available."""

    if not VIDEO_PATH.is_file():
        raise FileNotFoundError(
            "Video nicht gefunden:\n"
            f"{VIDEO_PATH}"
        )

    if not PARTICLE_BED_PREDICTION_DIR.is_dir():
        raise FileNotFoundError(
            "Particle-bed prediction directory not found:\n"
            f"{PARTICLE_BED_PREDICTION_DIR}"
        )

    if not INNER_PIPE_PREDICTION_DIR.is_dir():
        raise FileNotFoundError(
            "Inner-pipe prediction directory not found:\n"
            f"{INNER_PIPE_PREDICTION_DIR}"
        )


# =============================================================================
# Extraction
# =============================================================================

def extract_frames() -> list[dict]:
    """
    Extract selected original frames and copy matching prediction masks.

    Returns
    -------
    list[dict]
        Metadata for every selected frame.
    """

    cap = cv2.VideoCapture(
        str(VIDEO_PATH)
    )

    if not cap.isOpened():
        raise RuntimeError(
            "Video konnte nicht geöffnet werden:\n"
            f"{VIDEO_PATH}"
        )

    total_frames = int(
        cap.get(
            cv2.CAP_PROP_FRAME_COUNT
        )
    )

    fps = float(
        cap.get(
            cv2.CAP_PROP_FPS
        )
    )

    width = int(
        cap.get(
            cv2.CAP_PROP_FRAME_WIDTH
        )
    )

    height = int(
        cap.get(
            cv2.CAP_PROP_FRAME_HEIGHT
        )
    )

    print("=" * 80)
    print("GX010129 Ground-Truth Preparation")
    print("=" * 80)

    print(f"Video:                {VIDEO_PATH}")
    print(f"Video frames:         {total_frames}")
    print(f"FPS:                  {fps:.3f}")
    print(f"Resolution:           {width} x {height}")
    print(f"Selected frames:      {len(SELECTED_FRAMES)}")

    print()
    print("Objects:")
    print("  - particle_bed")
    print("  - inner_pipe")
    print()

    metadata: list[dict] = []

    for frame_number in SELECTED_FRAMES:

        # ---------------------------------------------------------------------
        # Validate requested frame number
        # ---------------------------------------------------------------------

        if (
            frame_number < 0
            or frame_number >= total_frames
        ):
            print(
                f"[WARNING] Frame {frame_number} is outside the "
                f"valid video range 0 ... {total_frames - 1}."
            )

            metadata.append(
                {
                    "frame": frame_number,
                    "time_seconds": "",
                    "frame_extracted": 0,
                    "particle_bed_prediction_found": 0,
                    "inner_pipe_prediction_found": 0,
                    "particle_bed_gt_created": 0,
                    "inner_pipe_gt_created": 0,
                }
            )

            continue

        # ---------------------------------------------------------------------
        # Extract original frame
        # ---------------------------------------------------------------------

        cap.set(
            cv2.CAP_PROP_POS_FRAMES,
            frame_number,
        )

        ok, frame = cap.read()

        if not ok:
            print(
                f"[ERROR] Frame {frame_number} could not be read."
            )

            metadata.append(
                {
                    "frame": frame_number,
                    "time_seconds": (
                        frame_number / fps
                        if fps > 0
                        else ""
                    ),
                    "frame_extracted": 0,
                    "particle_bed_prediction_found": 0,
                    "inner_pipe_prediction_found": 0,
                    "particle_bed_gt_created": 0,
                    "inner_pipe_gt_created": 0,
                }
            )

            continue

        output_frame_path = (
            frame_output_path(
                frame_number
            )
        )

        saved = cv2.imwrite(
            str(output_frame_path),
            frame,
        )

        if not saved:
            raise RuntimeError(
                "Frame could not be saved:\n"
                f"{output_frame_path}"
            )

        # ---------------------------------------------------------------------
        # Particle-bed prediction
        # ---------------------------------------------------------------------

        particle_source = (
            particle_bed_prediction_source_path(
                frame_number
            )
        )

        particle_found = (
            particle_source.is_file()
        )

        if particle_found:
            shutil.copy2(
                particle_source,
                particle_bed_prediction_output_path(
                    frame_number
                ),
            )

        # ---------------------------------------------------------------------
        # Inner-pipe prediction
        # ---------------------------------------------------------------------

        pipe_source = (
            inner_pipe_prediction_source_path(
                frame_number
            )
        )

        pipe_found = (
            pipe_source.is_file()
        )

        if pipe_found:
            shutil.copy2(
                pipe_source,
                inner_pipe_prediction_output_path(
                    frame_number
                ),
            )

        # ---------------------------------------------------------------------
        # Ground-truth status
        # ---------------------------------------------------------------------

        particle_gt_exists = (
            particle_bed_gt_path(
                frame_number
            ).is_file()
        )

        pipe_gt_exists = (
            inner_pipe_gt_path(
                frame_number
            ).is_file()
        )

        # ---------------------------------------------------------------------
        # Time
        # ---------------------------------------------------------------------

        time_seconds = (
            frame_number / fps
            if fps > 0
            else float("nan")
        )

        # ---------------------------------------------------------------------
        # Console output
        # ---------------------------------------------------------------------

        print(
            f"Frame {frame_number:6d} | "
            f"t={time_seconds:8.3f} s | "
            f"bed={'OK' if particle_found else 'MISSING':7s} | "
            f"pipe={'OK' if pipe_found else 'MISSING':7s}"
        )

        # ---------------------------------------------------------------------
        # Manifest row
        # ---------------------------------------------------------------------

        metadata.append(
            {
                "frame": frame_number,
                "time_seconds": time_seconds,
                "frame_extracted": 1,
                "particle_bed_prediction_found": (
                    1 if particle_found else 0
                ),
                "inner_pipe_prediction_found": (
                    1 if pipe_found else 0
                ),
                "particle_bed_gt_created": (
                    1 if particle_gt_exists else 0
                ),
                "inner_pipe_gt_created": (
                    1 if pipe_gt_exists else 0
                ),
            }
        )

    cap.release()

    return metadata


# =============================================================================
# Manifest
# =============================================================================

def save_manifest(
    metadata: list[dict],
) -> None:
    """Write information about all selected frames to CSV."""

    fieldnames = [
        "frame",
        "time_seconds",
        "frame_extracted",
        "particle_bed_prediction_found",
        "inner_pipe_prediction_found",
        "particle_bed_gt_created",
        "inner_pipe_gt_created",
    ]

    with MANIFEST_CSV.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as file:

        writer = csv.DictWriter(
            file,
            fieldnames=fieldnames,
        )

        writer.writeheader()

        writer.writerows(
            metadata
        )


# =============================================================================
# Summary
# =============================================================================

def print_summary(
    metadata: list[dict],
) -> None:
    """Print a concise extraction and preparation summary."""

    selected = len(
        metadata
    )

    extracted = sum(
        int(
            row[
                "frame_extracted"
            ]
        )
        for row in metadata
    )

    bed_predictions = sum(
        int(
            row[
                "particle_bed_prediction_found"
            ]
        )
        for row in metadata
    )

    pipe_predictions = sum(
        int(
            row[
                "inner_pipe_prediction_found"
            ]
        )
        for row in metadata
    )

    bed_gt = sum(
        int(
            row[
                "particle_bed_gt_created"
            ]
        )
        for row in metadata
    )

    pipe_gt = sum(
        int(
            row[
                "inner_pipe_gt_created"
            ]
        )
        for row in metadata
    )

    print()
    print("=" * 80)
    print("Summary")
    print("=" * 80)

    print(
        f"Selected frames:             {selected}"
    )

    print(
        f"Successfully extracted:      {extracted}"
    )

    print(
        f"Particle-bed predictions:    {bed_predictions}"
    )

    print(
        f"Inner-pipe predictions:      {pipe_predictions}"
    )

    print(
        f"Particle-bed GT available:   {bed_gt}"
    )

    print(
        f"Inner-pipe GT available:     {pipe_gt}"
    )

    print()
    print("Original frames:")
    print(
        f"  {FRAME_OUTPUT_DIR}"
    )

    print()
    print("Particle-bed predictions:")
    print(
        f"  {PARTICLE_BED_PREDICTION_OUTPUT_DIR}"
    )

    print()
    print("Inner-pipe predictions:")
    print(
        f"  {INNER_PIPE_PREDICTION_OUTPUT_DIR}"
    )

    print()
    print("Create manual particle-bed GT masks in:")
    print(
        f"  {PARTICLE_BED_GT_DIR}"
    )

    print()
    print("Create manual inner-pipe GT masks in:")
    print(
        f"  {INNER_PIPE_GT_DIR}"
    )

    print()
    print("Expected Ground-Truth file names:")

    print(
        "  particle bed:"
    )

    print(
        "    frame_XXXXXX_particle_bed_gt.png"
    )

    print(
        "  inner pipe:"
    )

    print(
        "    frame_XXXXXX_inner_pipe_gt.png"
    )

    print()
    print("Binary-mask convention:")

    print(
        "  0   = background"
    )

    print(
        "  255 = object"
    )

    print()
    print("Manifest:")
    print(
        f"  {MANIFEST_CSV}"
    )


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    """Program entry point."""

    validate_inputs()

    create_directories()

    metadata = extract_frames()

    save_manifest(
        metadata
    )

    print_summary(
        metadata
    )


if __name__ == "__main__":
    main()