#!/usr/bin/env python3
"""
validate_top_candidates_professional.py
=======================================
Repository-specific Stage-3 batch validation for the master-thesis project
``video_tracking_thesis``.
Purpose
-------
The repository already contains two preceding workflow stages:
* ``src/find_best_validation_dataset.py`` computes a coarse pre-ranking of
  candidate IMU measurements for each tracked video. Its CSV output uses the
  columns ``video_id``, ``imu_path`` and ``rank_for_video``.
* ``src/validate_video_vs_imu_v2.py`` performs the detailed validation of one
  video signal against one IMU signal through ``ValidationConfig``,
  ``ValidationResult`` and ``validate_video_vs_imu()``.
This Stage-3 program connects both stages without duplicating their signal
processing. It reads the pre-ranked candidates, selects one video, validates
its best candidates with the Stage-2 pipeline, resumes interrupted runs, and
writes a reproducible aggregate comparison.
Repository integration
----------------------
The program intentionally imports and uses the real repository modules:
* ``validate_video_vs_imu_v2.py``
* ``validation/video_loader.py``
* ``validation/imu_loader.py``
* ``validation/preprocessing.py``
* ``validation/synchronization.py``
* ``validation/metrics.py``
* ``validation/plotting.py``
* ``validation/report.py``
The last seven modules are imported explicitly during the compatibility check.
Their actual execution is delegated to ``validate_video_vs_imu()`` so that this
batch wrapper does not fork the scientific implementation.
Supported candidate schemas
---------------------------
Primary repository schema, generated by ``find_best_validation_dataset.py``::
    video_id,video_path,imu_measurement_id,imu_path,...,score,rank_for_video
Legacy schema, used by the earlier ``validate_top_candidates.py``::
    rank,imu_csv,label
Both ``imu_path`` and ``imu_csv`` are accepted. If both exist, ``imu_path``
has precedence. ``rank_for_video`` has precedence over ``rank``.
Outputs
-------
The selected output directory receives:
* one subdirectory per candidate, containing the normal Stage-2 artefacts;
* ``comparison.csv`` with successful runs in final ranking order;
* ``failures.csv`` with isolated candidate errors;
* ``summary.json`` with configuration, compatibility and complete results;
* ``summary.html`` with a browsable professional comparison;
* ``stage3.log`` with detailed run diagnostics;
* ``resume_state.json`` with durable per-candidate status information.
Resume semantics
----------------
With ``--resume``, completed candidates are not recomputed. Their existing
``validation_result.json`` is loaded and included in the new aggregate files.
Failed candidates are retried by default. Use ``--skip-failed-on-resume`` to
keep previous failures skipped.
Exit codes
----------
0
    All selected candidates completed successfully.
1
    At least one selected candidate failed, but aggregate files were written.
2
    Configuration, input or repository compatibility error.
130
    Interrupted by the user.
"""
from __future__ import annotations
import argparse
import csv
import dataclasses
import hashlib
import html
import importlib
import inspect
import json
import logging
import math
import os
import platform
import re
import shutil
import socket
import sys
import textwrap
import traceback
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from time import perf_counter
from typing import Any, Iterable, Iterator, Mapping, MutableMapping, Optional, Sequence
PROGRAM_NAME = "validate_top_candidates_professional"
PROGRAM_VERSION = "3.0.0"
LOGGER = logging.getLogger(PROGRAM_NAME)
CANDIDATE_FILE_COLUMNS = {
    "video_id",
    "video_path",
    "imu_measurement_id",
    "imu_path",
    "imu_csv",
    "score",
    "rank_for_video",
    "rank",
    "label",
}
COMPARISON_COLUMNS = [
    "final_rank",
    "source_rank",
    "rank_for_video",
    "video_id",
    "video_path",
    "imu_measurement_id",
    "label",
    "imu_path",
    "candidate_score",
    "pearson_correlation",
    "rmse",
    "normalized_rmse",
    "mae",
    "max_absolute_error",
    "r_squared",
    "video_dominant_frequency_hz",
    "imu_dominant_frequency_hz",
    "dominant_frequency_error_hz",
    "dominant_frequency_error_percent",
    "estimated_lag_s",
    "correlation_at_lag",
    "aligned_samples",
    "duration_s",
    "sample_rate_hz",
    "runtime_s",
    "status",
    "resumed",
    "run_directory",
    "validation_result_json",
    "report_html",
]
FAILURE_COLUMNS = [
    "source_rank",
    "rank_for_video",
    "video_id",
    "video_path",
    "imu_measurement_id",
    "label",
    "imu_path",
    "candidate_score",
    "status",
    "error_type",
    "error_message",
    "traceback_file",
    "run_directory",
    "timestamp_utc",
    "resumed",
]
class Stage3Error(RuntimeError):
    """Base class for controlled Stage-3 failures."""
class ConfigurationError(Stage3Error):
    """Raised when CLI or configuration values are inconsistent."""
class CandidateFormatError(Stage3Error):
    """Raised when the candidate CSV cannot be interpreted."""
class RepositoryCompatibilityError(Stage3Error):
    """Raised when required repository interfaces are missing."""
class ResumeStateError(Stage3Error):
    """Raised when persisted resume data is malformed."""
@dataclass(frozen=True, slots=True)
class Candidate:
    """Normalized candidate row from either supported CSV schema."""
    source_row: int
    source_rank: int
    rank_for_video: int
    video_id: str
    video_path: Optional[Path]
    imu_measurement_id: str
    imu_path: Path
    label: str
    score: Optional[float]
    raw: Mapping[str, str] = field(default_factory=dict, repr=False)
    @property
    def stable_id(self) -> str:
        """Return a deterministic identifier independent of CSV row order."""
        material = "|".join(
            (
                self.video_id,
                str(self.video_path or ""),
                self.imu_measurement_id,
                str(self.imu_path),
            )
        )
        digest = hashlib.sha256(material.encode("utf-8")).hexdigest()[:12]
        return f"r{self.rank_for_video:04d}-{digest}"
    @property
    def safe_label(self) -> str:
        """Return a filesystem-safe compact candidate label."""
        value = re.sub(r"[^A-Za-z0-9._-]+", "_", self.label.strip())
        value = value.strip("._-") or self.imu_measurement_id or "candidate"
        return value[:80]
    def to_dict(self) -> dict[str, Any]:
        return {
            "source_row": self.source_row,
            "source_rank": self.source_rank,
            "rank_for_video": self.rank_for_video,
            "video_id": self.video_id,
            "video_path": str(self.video_path) if self.video_path else None,
            "imu_measurement_id": self.imu_measurement_id,
            "imu_path": str(self.imu_path),
            "label": self.label,
            "score": self.score,
            "stable_id": self.stable_id,
        }
@dataclass(slots=True)
class Stage3Config:
    """Batch-level configuration mapped onto ``ValidationConfig`` fields."""
    candidates_csv: Path
    output_dir: Path
    video_csv: Optional[Path] = None
    video_id: Optional[str] = None
    top_k: int = 5
    resume: bool = False
    skip_failed_on_resume: bool = False
    overwrite_aggregate: bool = True
    video_time_column: Optional[str] = None
    video_value_column: Optional[str] = "inner_pipe_track_center_x"
    imu_time_column: Optional[str] = None
    imu_value_column: Optional[str] = "liny"
    video_fps: Optional[float] = None
    imu_sample_rate_hz: Optional[float] = None
    target_sample_rate_hz: Optional[float] = None
    video_scale: float = 1.0
    video_offset: float = 0.0
    imu_scale: float = 1.0
    imu_offset: float = 0.0
    start_time_s: Optional[float] = None
    end_time_s: Optional[float] = None
    detrend: bool = True
    center: bool = True
    normalize: str = "zscore"
    smoothing_window: int = 1
    lowpass_hz: Optional[float] = None
    highpass_hz: Optional[float] = None
    synchronization_method: str = "cross_correlation"
    max_lag_s: Optional[float] = None
    manual_lag_s: Optional[float] = None
    video_name: str = "video"
    imu_name: str = "imu"
    video_unit: Optional[str] = None
    imu_unit: Optional[str] = None
    report_title: str = "Video vs IMU candidate validation"
    author: Optional[str] = None
    save_intermediate: bool = True
    create_plots: bool = True
    create_report: bool = True
    strict_modules: bool = False
    continue_on_error: bool = True
    ranking_metric: str = "pearson_correlation"
    ranking_direction: str = "descending"
    secondary_metric: str = "rmse"
    secondary_direction: str = "ascending"
    progress: bool = True
    log_level: str = "INFO"
    def __post_init__(self) -> None:
        self.candidates_csv = self.candidates_csv.expanduser().resolve()
        self.output_dir = self.output_dir.expanduser().resolve()
        if self.video_csv is not None:
            self.video_csv = self.video_csv.expanduser().resolve()
        if self.top_k < 1:
            raise ConfigurationError("--top-k must be at least 1.")
        if self.smoothing_window < 1:
            raise ConfigurationError("--smoothing-window must be at least 1.")
        if self.normalize not in {"none", "zscore", "minmax", "robust"}:
            raise ConfigurationError(
                "--normalize must be none, zscore, minmax or robust."
            )
        if self.ranking_direction not in {"ascending", "descending"}:
            raise ConfigurationError("Invalid ranking direction.")
        if self.secondary_direction not in {"ascending", "descending"}:
            raise ConfigurationError("Invalid secondary ranking direction.")
        if self.start_time_s is not None and self.end_time_s is not None:
            if self.end_time_s <= self.start_time_s:
                raise ConfigurationError("end_time_s must be greater than start_time_s.")
@dataclass(slots=True)
class CompatibilityReport:
    """Result of repository import and interface inspection."""
    repository_root: Path
    source_directory: Path
    modules: dict[str, str]
    checks: list[dict[str, Any]]
    compatible: bool
    validation_config_fields: list[str]
    validation_result_fields: list[str]
    def to_dict(self) -> dict[str, Any]:
        return dataclasses.asdict(self)
@dataclass(slots=True)
class CandidateSuccess:
    """Normalized aggregate information from one ValidationResult."""
    candidate: Candidate
    metrics: dict[str, Any]
    synchronization: dict[str, Any]
    video_summary: dict[str, Any]
    imu_summary: dict[str, Any]
    runtime_s: float
    run_directory: Path
    result_json: Path
    report_html: Optional[Path]
    resumed: bool = False
    final_rank: Optional[int] = None
    def comparison_row(self) -> dict[str, Any]:
        metrics = self.metrics
        sync = self.synchronization
        return {
            "final_rank": self.final_rank,
            "source_rank": self.candidate.source_rank,
            "rank_for_video": self.candidate.rank_for_video,
            "video_id": self.candidate.video_id,
            "video_path": str(self.candidate.video_path or ""),
            "imu_measurement_id": self.candidate.imu_measurement_id,
            "label": self.candidate.label,
            "imu_path": str(self.candidate.imu_path),
            "candidate_score": self.candidate.score,
            "pearson_correlation": metric_value(metrics, "pearson_correlation"),
            "rmse": metric_value(metrics, "rmse"),
            "normalized_rmse": metric_value(metrics, "normalized_rmse"),
            "mae": metric_value(metrics, "mae"),
            "max_absolute_error": metric_value(metrics, "max_absolute_error"),
            "r_squared": metric_value(metrics, "r_squared"),
            "video_dominant_frequency_hz": metric_value(
                metrics, "video_dominant_frequency_hz"
            ),
            "imu_dominant_frequency_hz": metric_value(
                metrics, "imu_dominant_frequency_hz"
            ),
            "dominant_frequency_error_hz": metric_value(
                metrics, "dominant_frequency_error_hz"
            ),
            "dominant_frequency_error_percent": metric_value(
                metrics, "dominant_frequency_error_percent"
            ),
            "estimated_lag_s": first_non_null(
                metric_value(metrics, "estimated_lag_s"),
                metric_value(sync, "lag_s"),
            ),
            "correlation_at_lag": first_non_null(
                metric_value(metrics, "correlation_at_lag"),
                metric_value(sync, "correlation_at_lag"),
            ),
            "aligned_samples": metric_value(sync, "aligned_samples"),
            "duration_s": first_non_null(
                metric_value(metrics, "duration_s"),
                metric_value(self.video_summary, "duration_s"),
            ),
            "sample_rate_hz": first_non_null(
                metric_value(metrics, "sample_rate_hz"),
                metric_value(metrics, "sampling_rate_hz"),
            ),
            "runtime_s": self.runtime_s,
            "status": "success",
            "resumed": self.resumed,
            "run_directory": str(self.run_directory),
            "validation_result_json": str(self.result_json),
            "report_html": str(self.report_html) if self.report_html else "",
        }
@dataclass(slots=True)
class CandidateFailure:
    """Serializable isolated error for one candidate."""
    candidate: Candidate
    run_directory: Path
    error_type: str
    error_message: str
    traceback_file: Path
    timestamp_utc: str
    resumed: bool = False
    def csv_row(self) -> dict[str, Any]:
        return {
            "source_rank": self.candidate.source_rank,
            "rank_for_video": self.candidate.rank_for_video,
            "video_id": self.candidate.video_id,
            "video_path": str(self.candidate.video_path or ""),
            "imu_measurement_id": self.candidate.imu_measurement_id,
            "label": self.candidate.label,
            "imu_path": str(self.candidate.imu_path),
            "candidate_score": self.candidate.score,
            "status": "failure",
            "error_type": self.error_type,
            "error_message": self.error_message,
            "traceback_file": str(self.traceback_file),
            "run_directory": str(self.run_directory),
            "timestamp_utc": self.timestamp_utc,
            "resumed": self.resumed,
        }
@dataclass(slots=True)
class BatchSummary:
    """Complete in-memory representation of a Stage-3 run."""
    config: Stage3Config
    compatibility: CompatibilityReport
    selected_candidates: list[Candidate]
    successes: list[CandidateSuccess]
    failures: list[CandidateFailure]
    started_utc: str
    finished_utc: str
    runtime_s: float
    @property
    def best(self) -> Optional[CandidateSuccess]:
        return self.successes[0] if self.successes else None
# -----------------------------------------------------------------------------
# Generic utilities
# -----------------------------------------------------------------------------
def utc_now() -> str:
    """Return an ISO-8601 UTC timestamp with second precision."""
    return datetime.now(timezone.utc).isoformat(timespec="seconds")
def jsonable(value: Any) -> Any:
    """Convert dataclasses, paths and non-finite floats to strict JSON values."""
    if value is None or isinstance(value, (str, bool, int)):
        return value
    if isinstance(value, float):
        return value if math.isfinite(value) else None
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, datetime):
        return value.isoformat()
    if dataclasses.is_dataclass(value):
        return jsonable(dataclasses.asdict(value))
    if isinstance(value, Mapping):
        return {str(key): jsonable(item) for key, item in value.items()}
    if isinstance(value, (list, tuple, set, frozenset)):
        return [jsonable(item) for item in value]
    if hasattr(value, "item"):
        try:
            return jsonable(value.item())
        except Exception:
            pass
    if hasattr(value, "as_dict"):
        try:
            return jsonable(value.as_dict())
        except Exception:
            pass
    return str(value)
def write_json(path: Path, value: Any) -> Path:
    """Atomically write strict UTF-8 JSON."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump(jsonable(value), handle, ensure_ascii=False, indent=2, allow_nan=False)
        handle.write("\n")
    temporary.replace(path)
    return path
def read_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)
def parse_optional_float(value: Any) -> Optional[float]:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        number = float(text.replace(",", "."))
    except ValueError:
        return None
    return number if math.isfinite(number) else None
def parse_optional_int(value: Any) -> Optional[int]:
    number = parse_optional_float(value)
    return int(number) if number is not None else None
def first_non_empty(*values: Any) -> Optional[str]:
    for value in values:
        if value is not None and str(value).strip():
            return str(value).strip()
    return None
def first_non_null(*values: Any) -> Any:
    for value in values:
        if value is not None:
            return value
    return None
def metric_value(mapping: Mapping[str, Any], name: str) -> Any:
    """Read a metric while tolerating one level of nested dictionaries."""
    if name in mapping:
        return mapping[name]
    for value in mapping.values():
        if isinstance(value, Mapping) and name in value:
            return value[name]
    return None
def canonical_path(value: str, base_directory: Path) -> Path:
    """Resolve absolute or candidate-CSV-relative paths."""
    path = Path(os.path.expandvars(value)).expanduser()
    if not path.is_absolute():
        path = base_directory / path
    return path.resolve()
def normalize_identifier(value: str) -> str:
    """Normalize identifiers for case-insensitive video filtering."""
    return re.sub(r"[^a-z0-9]+", "", value.lower())
def infer_video_id(path: Optional[Path]) -> str:
    if path is None:
        return ""
    stem = path.stem
    for suffix in (
        "_results_inner_pipe_track_timeseries",
        "_inner_pipe_track_timeseries",
        "_timeseries",
        "_results",
    ):
        if stem.lower().endswith(suffix.lower()):
            return stem[: -len(suffix)]
    return stem
def infer_measurement_id(path: Path) -> str:
    if path.name.lower() == "data.csv" and path.parent.name:
        return path.parent.name
    return path.stem
def format_number(value: Any, digits: int = 6) -> str:
    if value is None or value == "":
        return ""
    try:
        number = float(value)
    except (TypeError, ValueError):
        return str(value)
    if not math.isfinite(number):
        return ""
    return f"{number:.{digits}g}"
def setup_logging(output_dir: Path, level: str) -> Path:
    """Configure console and persistent logging without duplicate handlers."""
    output_dir.mkdir(parents=True, exist_ok=True)
    log_file = output_dir / "stage3.log"
    root = logging.getLogger()
    root.handlers.clear()
    root.setLevel(getattr(logging, level.upper()))
    formatter = logging.Formatter(
        "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s"
    )
    console = logging.StreamHandler(sys.stderr)
    console.setFormatter(formatter)
    file_handler = logging.FileHandler(log_file, encoding="utf-8")
    file_handler.setFormatter(formatter)
    root.addHandler(console)
    root.addHandler(file_handler)
    return log_file
# -----------------------------------------------------------------------------
# Repository discovery and compatibility
# -----------------------------------------------------------------------------
def discover_repository_root(script_path: Path) -> Path:
    """Locate the repository root from this script's expected ``src`` location."""
    candidates = [script_path.parent, *script_path.parents]
    for candidate in candidates:
        if (candidate / "src" / "validate_video_vs_imu_v2.py").is_file():
            return candidate
        if candidate.name == "src" and (candidate / "validate_video_vs_imu_v2.py").is_file():
            return candidate.parent
    raise RepositoryCompatibilityError(
        "Could not locate repository root containing src/validate_video_vs_imu_v2.py."
    )
def ensure_import_paths(repository_root: Path) -> Path:
    """Expose ``src`` and register package modules under Stage-2 bare names.

    ``validation.plotting`` uses relative imports, while the current Stage-2
    orchestrator imports the same module as bare ``plotting``.  Importing the
    package modules first and registering aliases preserves both interfaces
    without changing the repository modules.
    """
    source = repository_root / "src"
    validation = source / "validation"
    for directory in (source, validation):
        text = str(directory)
        if text not in sys.path:
            sys.path.insert(0, text)
    for short_name in (
        "video_loader", "imu_loader", "preprocessing", "synchronization",
        "metrics", "plotting", "report",
    ):
        package_module = importlib.import_module(f"validation.{short_name}")
        sys.modules[short_name] = package_module
    return source
def check_repository_compatibility(repository_root: Path) -> CompatibilityReport:
    """Import and inspect every module explicitly required for Stage 3."""
    source = ensure_import_paths(repository_root)
    required_modules = (
        "validate_video_vs_imu_v2",
        "video_loader",
        "imu_loader",
        "preprocessing",
        "synchronization",
        "metrics",
        "plotting",
        "report",
    )
    modules: dict[str, str] = {}
    checks: list[dict[str, Any]] = []
    imported: dict[str, Any] = {}
    for name in required_modules:
        try:
            module = importlib.import_module(name)
            imported[name] = module
            modules[name] = str(Path(inspect.getfile(module)).resolve())
            checks.append({"check": f"import:{name}", "ok": True, "detail": modules[name]})
        except Exception as exc:
            checks.append({"check": f"import:{name}", "ok": False, "detail": repr(exc)})
    pipeline = imported.get("validate_video_vs_imu_v2")
    required_pipeline_symbols = (
        "ValidationConfig",
        "ValidationResult",
        "validate_video_vs_imu",
    )
    for symbol in required_pipeline_symbols:
        ok = pipeline is not None and hasattr(pipeline, symbol)
        checks.append(
            {
                "check": f"pipeline_symbol:{symbol}",
                "ok": ok,
                "detail": "present" if ok else "missing",
            }
        )
    module_symbols = {
        "video_loader": ("load_video_signal",),
        "imu_loader": ("load_imu_signal",),
        "preprocessing": ("preprocess_signal",),
        "synchronization": ("synchronize_signals",),
        "metrics": ("compute_validation_metrics",),
        "plotting": ("create_validation_plots",),
        "report": ("generate_report",),
    }
    for module_name, symbols in module_symbols.items():
        module = imported.get(module_name)
        for symbol in symbols:
            ok = module is not None and callable(getattr(module, symbol, None))
            checks.append(
                {
                    "check": f"module_symbol:{module_name}.{symbol}",
                    "ok": ok,
                    "detail": "callable" if ok else "missing or non-callable",
                }
            )
    config_fields: list[str] = []
    result_fields: list[str] = []
    if pipeline is not None and hasattr(pipeline, "ValidationConfig"):
        try:
            config_fields = [item.name for item in dataclasses.fields(pipeline.ValidationConfig)]
        except TypeError:
            pass
    if pipeline is not None and hasattr(pipeline, "ValidationResult"):
        try:
            result_fields = [item.name for item in dataclasses.fields(pipeline.ValidationResult)]
        except TypeError:
            pass
    required_config_fields = {"video_path", "imu_path", "output_dir"}
    config_ok = required_config_fields.issubset(config_fields)
    checks.append(
        {
            "check": "ValidationConfig required fields",
            "ok": config_ok,
            "detail": sorted(required_config_fields),
        }
    )
    required_result_fields = {"metrics", "synchronization", "runtime_s"}
    result_ok = required_result_fields.issubset(result_fields)
    checks.append(
        {
            "check": "ValidationResult required fields",
            "ok": result_ok,
            "detail": sorted(required_result_fields),
        }
    )
    compatible = all(bool(item["ok"]) for item in checks)
    return CompatibilityReport(
        repository_root=repository_root,
        source_directory=source,
        modules=modules,
        checks=checks,
        compatible=compatible,
        validation_config_fields=config_fields,
        validation_result_fields=result_fields,
    )
def import_stage2_api() -> tuple[type[Any], type[Any], Any]:
    """Import the exact Stage-2 public API after compatibility setup."""
    module = importlib.import_module("validate_video_vs_imu_v2")
    return module.ValidationConfig, module.ValidationResult, module.validate_video_vs_imu
# -----------------------------------------------------------------------------
# Candidate loading and selection
# -----------------------------------------------------------------------------
def sniff_csv_dialect(path: Path) -> csv.Dialect:
    sample = path.read_text(encoding="utf-8-sig", errors="replace")[:16384]
    try:
        return csv.Sniffer().sniff(sample, delimiters=",;\t|")
    except csv.Error:
        return csv.excel
def read_candidate_rows(path: Path) -> list[dict[str, str]]:
    """Read candidate CSV with delimiter and UTF-8 BOM handling."""
    if not path.is_file():
        raise FileNotFoundError(f"Candidate CSV not found: {path}")
    dialect = sniff_csv_dialect(path)
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle, dialect=dialect)
        if reader.fieldnames is None:
            raise CandidateFormatError("Candidate CSV has no header.")
        normalized_names = {str(name).strip() for name in reader.fieldnames if name}
        if not ({"imu_path", "imu_csv"} & normalized_names):
            raise CandidateFormatError(
                "Candidate CSV must contain either 'imu_path' or 'imu_csv'. "
                f"Columns found: {sorted(normalized_names)}"
            )
        return [
            {str(key).strip(): (value or "").strip() for key, value in row.items() if key}
            for row in reader
        ]
def normalize_candidate(
    row: Mapping[str, str],
    row_number: int,
    csv_directory: Path,
    default_video_path: Optional[Path],
) -> Candidate:
    """Normalize a repository or legacy candidate row."""
    imu_text = first_non_empty(row.get("imu_path"), row.get("imu_csv"))
    if not imu_text:
        raise CandidateFormatError(f"Row {row_number}: imu_path/imu_csv is empty.")
    imu_path = canonical_path(imu_text, csv_directory)
    video_text = first_non_empty(row.get("video_path"))
    video_path = canonical_path(video_text, csv_directory) if video_text else default_video_path
    video_id = first_non_empty(row.get("video_id"), infer_video_id(video_path)) or "unknown_video"
    measurement_id = first_non_empty(
        row.get("imu_measurement_id"),
        row.get("measurement_id"),
        infer_measurement_id(imu_path),
    ) or infer_measurement_id(imu_path)
    source_rank = parse_optional_int(row.get("rank")) or row_number
    rank_for_video = parse_optional_int(row.get("rank_for_video")) or source_rank
    score = parse_optional_float(row.get("score"))
    label = first_non_empty(row.get("label"), measurement_id, imu_path.parent.name) or "candidate"
    return Candidate(
        source_row=row_number,
        source_rank=source_rank,
        rank_for_video=rank_for_video,
        video_id=video_id,
        video_path=video_path,
        imu_measurement_id=measurement_id,
        imu_path=imu_path,
        label=label,
        score=score,
        raw=dict(row),
    )
def load_candidates(config: Stage3Config) -> list[Candidate]:
    rows = read_candidate_rows(config.candidates_csv)
    candidates: list[Candidate] = []
    errors: list[str] = []
    for index, row in enumerate(rows, start=1):
        try:
            candidates.append(
                normalize_candidate(
                    row,
                    index,
                    config.candidates_csv.parent,
                    config.video_csv,
                )
            )
        except Exception as exc:
            errors.append(f"row {index}: {exc}")
    if errors:
        raise CandidateFormatError(
            "Could not normalize all candidate rows:\n" + "\n".join(errors[:20])
        )
    if not candidates:
        raise CandidateFormatError("Candidate CSV contains no data rows.")
    return candidates
def select_video_id(candidates: Sequence[Candidate], requested: Optional[str]) -> str:
    """Resolve an explicit or unambiguous video identifier."""
    identifiers = sorted({candidate.video_id for candidate in candidates})
    if requested:
        target = normalize_identifier(requested)
        exact = [item for item in identifiers if normalize_identifier(item) == target]
        if len(exact) == 1:
            return exact[0]
        partial = [item for item in identifiers if target in normalize_identifier(item)]
        if len(partial) == 1:
            return partial[0]
        raise ConfigurationError(
            f"video_id '{requested}' did not resolve uniquely. Available: {identifiers}"
        )
    if len(identifiers) == 1:
        return identifiers[0]
    raise ConfigurationError(
        "Candidate CSV contains multiple video_id values. Use --video-id. "
        f"Available: {identifiers}"
    )
def select_candidates(config: Stage3Config, candidates: Sequence[Candidate]) -> list[Candidate]:
    selected_video_id = select_video_id(candidates, config.video_id)
    target = normalize_identifier(selected_video_id)
    selected = [
        candidate
        for candidate in candidates
        if normalize_identifier(candidate.video_id) == target
    ]
    selected.sort(
        key=lambda item: (
            item.rank_for_video,
            -item.score if item.score is not None else float("inf"),
            item.source_row,
        )
    )
    return selected[: config.top_k]
def validate_candidate_inputs(config: Stage3Config, candidates: Sequence[Candidate]) -> None:
    """Check all selected paths before expensive processing starts."""
    if not config.candidates_csv.is_file():
        raise FileNotFoundError(config.candidates_csv)
    if not candidates:
        raise ConfigurationError("No candidates selected after video_id/top-k filtering.")
    missing_imu = [str(item.imu_path) for item in candidates if not item.imu_path.is_file()]
    if missing_imu:
        raise FileNotFoundError(
            "Selected IMU files are missing:\n" + "\n".join(missing_imu)
        )
    for candidate in candidates:
        effective_video = config.video_csv or candidate.video_path
        if effective_video is None:
            raise ConfigurationError(
                f"Candidate {candidate.label} has no video_path and --video-csv was not set."
            )
        if not effective_video.is_file():
            raise FileNotFoundError(f"Video CSV not found: {effective_video}")
# -----------------------------------------------------------------------------
# Resume state and run-directory management
# -----------------------------------------------------------------------------
def candidate_run_directory(output_dir: Path, candidate: Candidate) -> Path:
    return output_dir / "candidates" / (
        f"rank_{candidate.rank_for_video:03d}_{candidate.safe_label}_{candidate.stable_id[-12:]}"
    )
def resume_state_path(output_dir: Path) -> Path:
    return output_dir / "resume_state.json"
def load_resume_state(output_dir: Path) -> dict[str, Any]:
    path = resume_state_path(output_dir)
    if not path.exists():
        return {"schema_version": 1, "candidates": {}}
    data = read_json(path)
    if not isinstance(data, Mapping) or not isinstance(data.get("candidates"), Mapping):
        raise ResumeStateError(f"Malformed resume state: {path}")
    return dict(data)
def update_resume_state(
    output_dir: Path,
    state: MutableMapping[str, Any],
    candidate: Candidate,
    status: str,
    run_directory: Path,
    detail: Optional[Mapping[str, Any]] = None,
) -> None:
    entries = state.setdefault("candidates", {})
    entries[candidate.stable_id] = {
        "candidate": candidate.to_dict(),
        "status": status,
        "run_directory": str(run_directory),
        "updated_utc": utc_now(),
        "detail": jsonable(detail or {}),
    }
    state["updated_utc"] = utc_now()
    write_json(resume_state_path(output_dir), state)
def find_report_html(result_data: Mapping[str, Any], run_directory: Path) -> Optional[Path]:
    artefacts = result_data.get("report_artifacts", {})
    candidates: list[Path] = []
    if isinstance(artefacts, Mapping):
        for key in ("html_path", "report_html", "html"):
            value = artefacts.get(key)
            if value:
                candidates.append(Path(str(value)))
    candidates.extend(
        (
            run_directory / "report" / "report.html",
            run_directory / "report.html",
        )
    )
    return next((path.resolve() for path in candidates if path.is_file()), None)
def success_from_result_data(
    candidate: Candidate,
    run_directory: Path,
    data: Mapping[str, Any],
    resumed: bool,
) -> CandidateSuccess:
    """Reconstruct a typed aggregate result from Stage-2 JSON."""
    metrics = data.get("metrics", {})
    synchronization = data.get("synchronization", {})
    if not isinstance(metrics, Mapping) or not isinstance(synchronization, Mapping):
        raise ResumeStateError(
            f"Existing result has invalid metrics/synchronization: {run_directory}"
        )
    result_json = run_directory / "validation_result.json"
    return CandidateSuccess(
        candidate=candidate,
        metrics=dict(metrics),
        synchronization=dict(synchronization),
        video_summary=dict(data.get("video_summary", {})),
        imu_summary=dict(data.get("imu_summary", {})),
        runtime_s=float(data.get("runtime_s") or 0.0),
        run_directory=run_directory,
        result_json=result_json,
        report_html=find_report_html(data, run_directory),
        resumed=resumed,
    )
def load_completed_candidate(candidate: Candidate, run_directory: Path) -> CandidateSuccess:
    path = run_directory / "validation_result.json"
    if not path.is_file():
        raise ResumeStateError(f"Missing validation result: {path}")
    data = read_json(path)
    if not isinstance(data, Mapping):
        raise ResumeStateError(f"Validation result is not a JSON object: {path}")
    return success_from_result_data(candidate, run_directory, data, resumed=True)
# -----------------------------------------------------------------------------
# Stage-2 invocation
# -----------------------------------------------------------------------------
def make_validation_config(
    config: Stage3Config,
    candidate: Candidate,
    run_directory: Path,
    ValidationConfig: type[Any],
) -> Any:
    """Map Stage-3 CLI values one-to-one onto repository ValidationConfig."""
    video_path = config.video_csv or candidate.video_path
    if video_path is None:
        raise ConfigurationError(f"No video path for candidate {candidate.label}.")
    kwargs = {
        "video_path": video_path,
        "imu_path": candidate.imu_path,
        "output_dir": run_directory,
        "video_time_column": config.video_time_column,
        "video_value_column": config.video_value_column,
        "imu_time_column": config.imu_time_column,
        "imu_value_column": config.imu_value_column,
        "video_fps": config.video_fps,
        "imu_sample_rate_hz": config.imu_sample_rate_hz,
        "video_scale": config.video_scale,
        "video_offset": config.video_offset,
        "imu_scale": config.imu_scale,
        "imu_offset": config.imu_offset,
        "start_time_s": config.start_time_s,
        "end_time_s": config.end_time_s,
        "detrend": config.detrend,
        "center": config.center,
        "normalize": config.normalize,
        "smoothing_window": config.smoothing_window,
        "lowpass_hz": config.lowpass_hz,
        "highpass_hz": config.highpass_hz,
        "synchronization_method": config.synchronization_method,
        "max_lag_s": config.max_lag_s,
        "manual_lag_s": config.manual_lag_s,
        "target_sample_rate_hz": config.target_sample_rate_hz,
        "video_name": config.video_name,
        "imu_name": config.imu_name,
        "video_unit": config.video_unit,
        "imu_unit": config.imu_unit,
        "report_title": config.report_title,
        "run_name": f"{candidate.video_id} candidate {candidate.rank_for_video}: {candidate.label}",
        "author": config.author,
        "save_intermediate": config.save_intermediate,
        "create_plots": config.create_plots,
        "create_report": config.create_report,
        "overwrite": True,
        "strict_modules": config.strict_modules,
        "extra": {
            "stage": 3,
            "stage3_program": PROGRAM_NAME,
            "stage3_version": PROGRAM_VERSION,
            "candidate": candidate.to_dict(),
            "candidates_csv": str(config.candidates_csv),
        },
    }
    supported = {field.name for field in dataclasses.fields(ValidationConfig)}
    return ValidationConfig(**{key: value for key, value in kwargs.items() if key in supported})
def run_candidate(
    config: Stage3Config,
    candidate: Candidate,
    run_directory: Path,
    ValidationConfig: type[Any],
    ValidationResult: type[Any],
    validate_video_vs_imu: Any,
) -> CandidateSuccess:
    """Execute one candidate through the unmodified Stage-2 pipeline."""
    run_directory.mkdir(parents=True, exist_ok=True)
    validation_config = make_validation_config(
        config, candidate, run_directory, ValidationConfig
    )
    write_json(run_directory / "stage3_candidate.json", candidate.to_dict())
    LOGGER.info("Starting candidate rank=%s label=%s", candidate.rank_for_video, candidate.label)
    result = validate_video_vs_imu(validation_config)
    if not isinstance(result, ValidationResult):
        raise TypeError(
            "validate_video_vs_imu() returned "
            f"{type(result).__name__}, expected ValidationResult."
        )
    result_data = result.as_dict() if hasattr(result, "as_dict") else dataclasses.asdict(result)
    result_json = run_directory / "validation_result.json"
    if not result_json.is_file():
        write_json(result_json, result_data)
    return success_from_result_data(candidate, run_directory, result_data, resumed=False)
def record_failure(candidate: Candidate, run_directory: Path, exc: BaseException) -> CandidateFailure:
    """Persist a full traceback while keeping CSV/HTML messages compact."""
    run_directory.mkdir(parents=True, exist_ok=True)
    trace_path = run_directory / "failure_traceback.txt"
    trace_text = "".join(traceback.format_exception(type(exc), exc, exc.__traceback__))
    trace_path.write_text(trace_text, encoding="utf-8", newline="\n")
    failure = CandidateFailure(
        candidate=candidate,
        run_directory=run_directory,
        error_type=type(exc).__name__,
        error_message=str(exc),
        traceback_file=trace_path,
        timestamp_utc=utc_now(),
    )
    write_json(run_directory / "failure.json", failure.csv_row())
    return failure
# -----------------------------------------------------------------------------
# Ranking and aggregate exports
# -----------------------------------------------------------------------------
def sortable_metric(value: Any, direction: str) -> float:
    number = parse_optional_float(value)
    if number is None:
        return float("inf")
    return -number if direction == "descending" else number
def rank_successes(config: Stage3Config, successes: Sequence[CandidateSuccess]) -> list[CandidateSuccess]:
    ranked = list(successes)
    ranked.sort(
        key=lambda item: (
            sortable_metric(metric_value(item.metrics, config.ranking_metric), config.ranking_direction),
            sortable_metric(metric_value(item.metrics, config.secondary_metric), config.secondary_direction),
            item.candidate.rank_for_video,
        )
    )
    for index, item in enumerate(ranked, start=1):
        item.final_rank = index
    return ranked
def write_csv(path: Path, rows: Sequence[Mapping[str, Any]], columns: Sequence[str]) -> Path:
    """Always write a header, even when there are no rows."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(columns), extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({key: jsonable(row.get(key)) for key in columns})
    temporary.replace(path)
    return path
def relative_link(target: Optional[Path], origin_directory: Path) -> str:
    if target is None:
        return ""
    try:
        return os.path.relpath(target, origin_directory).replace(os.sep, "/")
    except ValueError:
        return target.as_uri()
def html_metric(value: Any) -> str:
    text = format_number(value)
    return html.escape(text if text else "—")
def render_summary_html(summary: BatchSummary) -> str:
    """Render a self-contained aggregate report without external assets."""
    config = summary.config
    best = summary.best
    rows: list[str] = []
    for item in summary.successes:
        row = item.comparison_row()
        report_link = relative_link(item.report_html, config.output_dir)
        result_link = relative_link(item.result_json, config.output_dir)
        report_cell = (
            f'<a href="{html.escape(report_link, quote=True)}">report</a>'
            if report_link else "—"
        )
        rows.append(
            "<tr>"
            f"<td>{item.final_rank}</td>"
            f"<td>{item.candidate.rank_for_video}</td>"
            f"<td>{html.escape(item.candidate.label)}</td>"
            f"<td><code>{html.escape(item.candidate.imu_measurement_id)}</code></td>"
            f"<td>{html_metric(row['candidate_score'])}</td>"
            f"<td>{html_metric(row['pearson_correlation'])}</td>"
            f"<td>{html_metric(row['rmse'])}</td>"
            f"<td>{html_metric(row['mae'])}</td>"
            f"<td>{html_metric(row['r_squared'])}</td>"
            f"<td>{html_metric(row['estimated_lag_s'])}</td>"
            f"<td>{html_metric(row['dominant_frequency_error_hz'])}</td>"
            f"<td>{'yes' if item.resumed else 'no'}</td>"
            f"<td>{report_cell} · <a href=\"{html.escape(result_link, quote=True)}\">json</a></td>"
            "</tr>"
        )
    failure_rows: list[str] = []
    for failure in summary.failures:
        trace_link = relative_link(failure.traceback_file, config.output_dir)
        failure_rows.append(
            "<tr>"
            f"<td>{failure.candidate.rank_for_video}</td>"
            f"<td>{html.escape(failure.candidate.label)}</td>"
            f"<td>{html.escape(failure.error_type)}</td>"
            f"<td>{html.escape(failure.error_message)}</td>"
            f"<td><a href=\"{html.escape(trace_link, quote=True)}\">traceback</a></td>"
            "</tr>"
        )
    best_html = "<p>No successful candidate.</p>"
    if best is not None:
        best_row = best.comparison_row()
        best_html = (
            f"<p><strong>{html.escape(best.candidate.label)}</strong> "
            f"(final rank {best.final_rank}, source rank {best.candidate.rank_for_video})</p>"
            "<dl>"
            f"<dt>Pearson correlation</dt><dd>{html_metric(best_row['pearson_correlation'])}</dd>"
            f"<dt>RMSE</dt><dd>{html_metric(best_row['rmse'])}</dd>"
            f"<dt>MAE</dt><dd>{html_metric(best_row['mae'])}</dd>"
            f"<dt>Estimated lag [s]</dt><dd>{html_metric(best_row['estimated_lag_s'])}</dd>"
            "</dl>"
        )
    compatibility_rows = "".join(
        "<tr>"
        f"<td>{html.escape(str(item['check']))}</td>"
        f"<td class=\"{'ok' if item['ok'] else 'bad'}\">{'OK' if item['ok'] else 'FAILED'}</td>"
        f"<td><code>{html.escape(str(item['detail']))}</code></td>"
        "</tr>"
        for item in summary.compatibility.checks
    )
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Stage 3 candidate validation</title>
<style>
:root {{ --bg:#f4f7fb; --card:#fff; --text:#17202a; --muted:#5d6d7e; --line:#d9e2ec; --accent:#155eef; --good:#16794b; --bad:#b42318; }}
* {{ box-sizing:border-box; }}
body {{ margin:0; font-family:system-ui,-apple-system,"Segoe UI",sans-serif; background:var(--bg); color:var(--text); line-height:1.5; }}
main {{ max-width:1500px; margin:auto; padding:24px; }}
header,section {{ background:var(--card); border:1px solid var(--line); border-radius:12px; padding:20px; margin-bottom:16px; box-shadow:0 2px 8px rgba(16,24,40,.04); }}
h1,h2 {{ color:var(--accent); margin-top:0; }}
.meta {{ color:var(--muted); }}
.grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(180px,1fr)); gap:12px; }}
.kpi {{ border:1px solid var(--line); border-radius:8px; padding:12px; }}
.kpi strong {{ display:block; font-size:1.6rem; }}
.table-wrap {{ overflow-x:auto; }}
table {{ width:100%; border-collapse:collapse; font-size:.92rem; }}
th,td {{ border-bottom:1px solid var(--line); padding:9px; text-align:left; vertical-align:top; white-space:nowrap; }}
th {{ position:sticky; top:0; background:#eef4ff; }}
code {{ white-space:normal; overflow-wrap:anywhere; }}
a {{ color:var(--accent); }}
.ok {{ color:var(--good); font-weight:700; }}
.bad {{ color:var(--bad); font-weight:700; }}
dl {{ display:grid; grid-template-columns:max-content 1fr; gap:6px 16px; }}
dt {{ font-weight:600; }} dd {{ margin:0; }}
</style>
</head>
<body><main>
<header>
<h1>Stage 3: Top-candidate validation</h1>
<p class="meta">Program {PROGRAM_VERSION} · started {html.escape(summary.started_utc)} · finished {html.escape(summary.finished_utc)} · runtime {summary.runtime_s:.3f} s</p>
<p><strong>Video ID:</strong> {html.escape(summary.selected_candidates[0].video_id if summary.selected_candidates else '')}<br>
<strong>Candidate source:</strong> <code>{html.escape(str(config.candidates_csv))}</code><br>
<strong>Ranking:</strong> {html.escape(config.ranking_metric)} ({html.escape(config.ranking_direction)}), then {html.escape(config.secondary_metric)} ({html.escape(config.secondary_direction)})</p>
</header>
<section><h2>Run overview</h2><div class="grid">
<div class="kpi"><span>Selected</span><strong>{len(summary.selected_candidates)}</strong></div>
<div class="kpi"><span>Successful</span><strong>{len(summary.successes)}</strong></div>
<div class="kpi"><span>Failed</span><strong>{len(summary.failures)}</strong></div>
<div class="kpi"><span>Resumed</span><strong>{sum(item.resumed for item in summary.successes)}</strong></div>
</div></section>
<section><h2>Best candidate</h2>{best_html}</section>
<section><h2>Final comparison</h2><div class="table-wrap"><table>
<thead><tr><th>Final</th><th>Source</th><th>Label</th><th>Measurement</th><th>Pre-score</th><th>Pearson</th><th>RMSE</th><th>MAE</th><th>R²</th><th>Lag [s]</th><th>Δf [Hz]</th><th>Resumed</th><th>Artefacts</th></tr></thead>
<tbody>{''.join(rows) if rows else '<tr><td colspan="13">No successful results.</td></tr>'}</tbody>
</table></div></section>
<section><h2>Failures</h2><div class="table-wrap"><table>
<thead><tr><th>Source rank</th><th>Label</th><th>Type</th><th>Message</th><th>Diagnostic</th></tr></thead>
<tbody>{''.join(failure_rows) if failure_rows else '<tr><td colspan="5">No failures.</td></tr>'}</tbody>
</table></div></section>
<section><h2>Repository compatibility</h2><div class="table-wrap"><table>
<thead><tr><th>Check</th><th>Status</th><th>Detail</th></tr></thead><tbody>{compatibility_rows}</tbody>
</table></div></section>
</main></body></html>"""
def summary_payload(summary: BatchSummary) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "program": PROGRAM_NAME,
        "program_version": PROGRAM_VERSION,
        "started_utc": summary.started_utc,
        "finished_utc": summary.finished_utc,
        "runtime_s": summary.runtime_s,
        "environment": {
            "python": sys.version.replace("\n", " "),
            "executable": sys.executable,
            "platform": platform.platform(),
            "hostname": socket.gethostname(),
            "working_directory": str(Path.cwd()),
        },
        "configuration": dataclasses.asdict(summary.config),
        "repository_compatibility": summary.compatibility.to_dict(),
        "counts": {
            "selected": len(summary.selected_candidates),
            "successful": len(summary.successes),
            "failed": len(summary.failures),
            "resumed": sum(item.resumed for item in summary.successes),
        },
        "best_candidate": summary.best.comparison_row() if summary.best else None,
        "selected_candidates": [item.to_dict() for item in summary.selected_candidates],
        "results": [item.comparison_row() for item in summary.successes],
        "failures": [item.csv_row() for item in summary.failures],
    }
def write_aggregate_outputs(summary: BatchSummary) -> None:
    output = summary.config.output_dir
    comparison_rows = [item.comparison_row() for item in summary.successes]
    failure_rows = [item.csv_row() for item in summary.failures]
    write_csv(output / "comparison.csv", comparison_rows, COMPARISON_COLUMNS)
    write_csv(output / "failures.csv", failure_rows, FAILURE_COLUMNS)
    write_json(output / "summary.json", summary_payload(summary))
    html_text = render_summary_html(summary)
    temporary = output / "summary.html.tmp"
    temporary.write_text(html_text, encoding="utf-8", newline="\n")
    temporary.replace(output / "summary.html")
# -----------------------------------------------------------------------------
# Progress and orchestration
# -----------------------------------------------------------------------------
def progress_message(index: int, total: int, candidate: Candidate, status: str) -> str:
    width = 28
    completed = min(width, int(width * index / max(total, 1)))
    bar = "#" * completed + "-" * (width - completed)
    return (
        f"[{bar}] {index:>3}/{total:<3} {status:<9} "
        f"rank={candidate.rank_for_video:<3} {candidate.label}"
    )
def emit_progress(config: Stage3Config, index: int, total: int, candidate: Candidate, status: str) -> None:
    if config.progress:
        print(progress_message(index, total, candidate, status), file=sys.stderr, flush=True)
def run_batch(config: Stage3Config, compatibility: CompatibilityReport) -> BatchSummary:
    """Run, resume, rank and export the selected top candidates."""
    started_clock = perf_counter()
    started_utc = utc_now()
    all_candidates = load_candidates(config)
    selected = select_candidates(config, all_candidates)
    validate_candidate_inputs(config, selected)
    ValidationConfig, ValidationResult, validate_video_vs_imu = import_stage2_api()
    state = load_resume_state(config.output_dir)
    successes: list[CandidateSuccess] = []
    failures: list[CandidateFailure] = []
    for index, candidate in enumerate(selected, start=1):
        run_directory = candidate_run_directory(config.output_dir, candidate)
        result_file = run_directory / "validation_result.json"
        previous = state.get("candidates", {}).get(candidate.stable_id, {})
        previous_status = previous.get("status") if isinstance(previous, Mapping) else None
        if config.resume and result_file.is_file():
            try:
                success = load_completed_candidate(candidate, run_directory)
                successes.append(success)
                update_resume_state(
                    config.output_dir, state, candidate, "success", run_directory,
                    {"resumed": True, "validation_result": str(result_file)},
                )
                emit_progress(config, index, len(selected), candidate, "resumed")
                LOGGER.info("Resumed candidate %s from %s", candidate.label, result_file)
                continue
            except Exception as exc:
                LOGGER.warning("Existing result for %s is unusable: %s", candidate.label, exc)
        if (
            config.resume
            and config.skip_failed_on_resume
            and previous_status == "failure"
            and (run_directory / "failure.json").is_file()
        ):
            failure_data = read_json(run_directory / "failure.json")
            failure = CandidateFailure(
                candidate=candidate,
                run_directory=run_directory,
                error_type=str(failure_data.get("error_type", "PreviousFailure")),
                error_message=str(failure_data.get("error_message", "previous failure")),
                traceback_file=Path(str(failure_data.get("traceback_file", run_directory / "failure_traceback.txt"))),
                timestamp_utc=str(failure_data.get("timestamp_utc", utc_now())),
                resumed=True,
            )
            failures.append(failure)
            emit_progress(config, index, len(selected), candidate, "skipped")
            continue
        try:
            emit_progress(config, index - 1, len(selected), candidate, "running")
            update_resume_state(config.output_dir, state, candidate, "running", run_directory)
            success = run_candidate(
                config,
                candidate,
                run_directory,
                ValidationConfig,
                ValidationResult,
                validate_video_vs_imu,
            )
            successes.append(success)
            update_resume_state(
                config.output_dir,
                state,
                candidate,
                "success",
                run_directory,
                {"validation_result": str(success.result_json), "runtime_s": success.runtime_s},
            )
            emit_progress(config, index, len(selected), candidate, "success")
        except KeyboardInterrupt:
            update_resume_state(config.output_dir, state, candidate, "interrupted", run_directory)
            raise
        except Exception as exc:
            LOGGER.exception("Candidate rank=%s failed", candidate.rank_for_video)
            failure = record_failure(candidate, run_directory, exc)
            failures.append(failure)
            update_resume_state(
                config.output_dir,
                state,
                candidate,
                "failure",
                run_directory,
                failure.csv_row(),
            )
            emit_progress(config, index, len(selected), candidate, "failure")
            if not config.continue_on_error:
                break
    ranked = rank_successes(config, successes)
    summary = BatchSummary(
        config=config,
        compatibility=compatibility,
        selected_candidates=selected,
        successes=ranked,
        failures=failures,
        started_utc=started_utc,
        finished_utc=utc_now(),
        runtime_s=perf_counter() - started_clock,
    )
    write_aggregate_outputs(summary)
    return summary
# -----------------------------------------------------------------------------
# Command-line interface
# -----------------------------------------------------------------------------
def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog=PROGRAM_NAME,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description=(
            "Validate the top IMU candidates from find_best_validation_dataset.py "
            "using the repository's validate_video_vs_imu_v2 Stage-2 pipeline."
        ),
    )
    io_group = parser.add_argument_group("input and selection")
    io_group.add_argument("--candidates-csv", required=True, type=Path)
    io_group.add_argument(
        "--video-csv", "--video-path", dest="video_csv", type=Path,
        help="Override video_path from the candidate CSV for every selected row.",
    )
    io_group.add_argument(
        "--video-id",
        help="Filter candidates by repository video_id; required for multi-video CSV files.",
    )
    io_group.add_argument("--top-k", type=int, default=5)
    io_group.add_argument("--output-dir", required=True, type=Path)
    resume_group = parser.add_argument_group("resume and error policy")
    resume_group.add_argument("--resume", action="store_true")
    resume_group.add_argument("--skip-failed-on-resume", action="store_true")
    resume_group.add_argument("--fail-fast", action="store_true")
    signal_group = parser.add_argument_group("signal columns and units")
    signal_group.add_argument("--video-time-column")
    signal_group.add_argument(
        "--video-value-column", "--signal-column",
        dest="video_value_column", default="inner_pipe_track_center_x",
    )
    signal_group.add_argument("--imu-time-column")
    signal_group.add_argument(
        "--imu-value-column", "--imu-axis",
        dest="imu_value_column", default="liny",
    )
    signal_group.add_argument("--video-fps", type=float)
    signal_group.add_argument("--imu-sample-rate-hz", type=float)
    signal_group.add_argument("--target-sample-rate-hz", type=float)
    signal_group.add_argument("--video-name", default="video")
    signal_group.add_argument("--imu-name", default="imu")
    signal_group.add_argument("--video-unit")
    signal_group.add_argument("--imu-unit")
    preprocess_group = parser.add_argument_group("preprocessing")
    preprocess_group.add_argument("--video-scale", type=float, default=1.0)
    preprocess_group.add_argument("--video-offset", type=float, default=0.0)
    preprocess_group.add_argument("--imu-scale", type=float, default=1.0)
    preprocess_group.add_argument("--imu-offset", type=float, default=0.0)
    preprocess_group.add_argument("--start-time-s", type=float)
    preprocess_group.add_argument("--end-time-s", type=float)
    preprocess_group.add_argument("--no-detrend", action="store_true")
    preprocess_group.add_argument("--no-center", action="store_true")
    preprocess_group.add_argument(
        "--normalize", choices=("none", "zscore", "minmax", "robust"), default="zscore"
    )
    preprocess_group.add_argument("--smoothing-window", type=int, default=1)
    preprocess_group.add_argument("--lowpass-hz", type=float)
    preprocess_group.add_argument("--highpass-hz", type=float)
    sync_group = parser.add_argument_group("synchronization")
    sync_group.add_argument(
        "--synchronization-method",
        choices=("cross_correlation", "timestamp", "none"),
        default="cross_correlation",
    )
    sync_group.add_argument("--max-lag-s", type=float)
    sync_group.add_argument("--manual-lag-s", type=float)
    output_group = parser.add_argument_group("reports and ranking")
    output_group.add_argument("--report-title", default="Video vs IMU candidate validation")
    output_group.add_argument("--author")
    output_group.add_argument("--no-intermediate", action="store_true")
    output_group.add_argument("--no-plots", action="store_true")
    output_group.add_argument("--no-report", action="store_true")
    output_group.add_argument("--strict-modules", action="store_true")
    output_group.add_argument("--ranking-metric", default="pearson_correlation")
    output_group.add_argument(
        "--ranking-direction", choices=("ascending", "descending"), default="descending"
    )
    output_group.add_argument("--secondary-metric", default="rmse")
    output_group.add_argument(
        "--secondary-direction", choices=("ascending", "descending"), default="ascending"
    )
    output_group.add_argument("--no-progress", action="store_true")
    output_group.add_argument(
        "--log-level", choices=("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"),
        default="INFO",
    )
    output_group.add_argument("--check-only", action="store_true")
    output_group.add_argument("--version", action="version", version=PROGRAM_VERSION)
    return parser
def config_from_args(args: argparse.Namespace) -> Stage3Config:
    return Stage3Config(
        candidates_csv=args.candidates_csv,
        output_dir=args.output_dir,
        video_csv=args.video_csv,
        video_id=args.video_id,
        top_k=args.top_k,
        resume=args.resume,
        skip_failed_on_resume=args.skip_failed_on_resume,
        video_time_column=args.video_time_column,
        video_value_column=args.video_value_column,
        imu_time_column=args.imu_time_column,
        imu_value_column=args.imu_value_column,
        video_fps=args.video_fps,
        imu_sample_rate_hz=args.imu_sample_rate_hz,
        target_sample_rate_hz=args.target_sample_rate_hz,
        video_scale=args.video_scale,
        video_offset=args.video_offset,
        imu_scale=args.imu_scale,
        imu_offset=args.imu_offset,
        start_time_s=args.start_time_s,
        end_time_s=args.end_time_s,
        detrend=not args.no_detrend,
        center=not args.no_center,
        normalize=args.normalize,
        smoothing_window=args.smoothing_window,
        lowpass_hz=args.lowpass_hz,
        highpass_hz=args.highpass_hz,
        synchronization_method=args.synchronization_method,
        max_lag_s=args.max_lag_s,
        manual_lag_s=args.manual_lag_s,
        video_name=args.video_name,
        imu_name=args.imu_name,
        video_unit=args.video_unit,
        imu_unit=args.imu_unit,
        report_title=args.report_title,
        author=args.author,
        save_intermediate=not args.no_intermediate,
        create_plots=not args.no_plots,
        create_report=not args.no_report,
        strict_modules=args.strict_modules,
        continue_on_error=not args.fail_fast,
        ranking_metric=args.ranking_metric,
        ranking_direction=args.ranking_direction,
        secondary_metric=args.secondary_metric,
        secondary_direction=args.secondary_direction,
        progress=not args.no_progress,
        log_level=args.log_level,
    )
def print_final_summary(summary: BatchSummary) -> None:
    print("=" * 88)
    print("STAGE 3 FINAL RANKING")
    print("=" * 88)
    if not summary.successes:
        print("No candidate completed successfully.")
    for item in summary.successes:
        row = item.comparison_row()
        print(
            f"{item.final_rank:>2}. source={item.candidate.rank_for_video:<3} "
            f"{item.candidate.label:<28.28} "
            f"Pearson={format_number(row['pearson_correlation'], 5):>9} "
            f"RMSE={format_number(row['rmse'], 5):>9} "
            f"Lag={format_number(row['estimated_lag_s'], 5):>9}"
        )
    print("-" * 88)
    print(f"Successful: {len(summary.successes)} | Failed: {len(summary.failures)}")
    print(f"comparison.csv: {summary.config.output_dir / 'comparison.csv'}")
    print(f"summary.html:   {summary.config.output_dir / 'summary.html'}")
    if summary.best:
        print(f"Best candidate: {summary.best.candidate.label}")
def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        config = config_from_args(args)
        config.output_dir.mkdir(parents=True, exist_ok=True)
        setup_logging(config.output_dir, config.log_level)
        script_path = Path(__file__).resolve()
        repository_root = discover_repository_root(script_path)
        compatibility = check_repository_compatibility(repository_root)
        write_json(config.output_dir / "repository_compatibility.json", compatibility.to_dict())
        if not compatibility.compatible:
            failed = [item for item in compatibility.checks if not item["ok"]]
            raise RepositoryCompatibilityError(
                "Repository compatibility check failed:\n"
                + "\n".join(f"- {item['check']}: {item['detail']}" for item in failed)
            )
        LOGGER.info("Repository compatibility verified: %s", repository_root)
        if args.check_only:
            print(json.dumps(jsonable(compatibility.to_dict()), ensure_ascii=False, indent=2))
            return 0
        summary = run_batch(config, compatibility)
        print_final_summary(summary)
        return 1 if summary.failures else 0
    except KeyboardInterrupt:
        LOGGER.error("Stage-3 validation interrupted by user.")
        return 130
    except (Stage3Error, FileNotFoundError, ValueError) as exc:
        LOGGER.error("%s", exc)
        return 2
    except Exception as exc:
        LOGGER.exception("Unexpected Stage-3 failure: %s", exc)
        return 2
if __name__ == "__main__":
    raise SystemExit(main())
